spring:
  datasource:
    druid:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 199097
      url: jdbc:mysql://localhost:3306/db5?serverTimeZone=UTC

#  elasticsearch:
#    uris: http://localhost:9200

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
