spring:
  task:
    scheduling:
      # 任务调度线程池大小 默认：1
      pool:
        size: 1
      shutdown:
        #线程池关闭时是否等待所有任务完成
        await-termination: false
        #调度线程关闭前最大等待时间，确保最后一定关闭
        await-termination-period: 10s
      # 调度线程名称前缀
      thread-name-prefix: spring_task_