server:
  port: 80


spring:
  activemq:
    broker-url: tcp://localhost:61616

  jms:
    template:
      default-destination: zhangjihe
    pub-sub-domain: true

  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order


rocketmq:
  name-server: localhost:9876
  producer:
    group: group_rocketmq
