spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db5?serverTimezone=UTC
    username: root
    password: 199097
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
