spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db5
      username: root
      password: 199097

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db5
#    username: root
#    password: 199097
#    type: com.alibaba.druid.pool.DruidDataSource